[chat_completion]
# this will be filled automatically based on your input
active_model = ""
# local path of your ollama port, the given one is the default
base_url = "http://localhost:11434"

# add model names here to show them as options in the terminal prompt -> for easier access  :)
[configured_models]
large_language_models = []

# paths related to DoxyGen
[doxygen_config]
doxyfile_path = "your path"
doxygen_directory_path = "your path"
