[chat_completion]
# this will be filled automatically based on your input
active_model = ""
# local path of your ollama port
base_url = "http://localhost:11434"

# add model names here to show them as options in the terminal prompt -> for easier access  :)
[configured_models]
large_language_models = []

# paths related to doxygen
[doxygen_config]
doxyfile_path = "/Users/mehnert/prototype-cpp-doc-generator/Doxyfile"
doxygen_directory_path = "/Users/mehnert/prototype-cpp-doc-generator/doxygen_output"
