[chat_completion]
active_model = "deepseek-coder-v2:latest"
base_url = "http://localhost:1434"

[configured_models]
large_language_models = [ "llama3", "gemma:7b", "deepseek-coder-v2:latest", "test",]
